name: CI

on: [push, workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-arm64.tgz
        tar -xzf ngrok-v3-stable-linux-arm64.tgz
        sudo mv ngrok /usr/local/bin/
    - name: Update ngrok
      run: |
        /usr/local/bin/ngrok update
    - name: Auth
      run: /usr/local/bin/ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Create Tunnel
      run: |
        /usr/local/bin/ngrok tcp 3389 &
        sleep 10
        curl -s http://localhost:4040/api/tunnels | jq '.tunnels[0].public_url'
