name: Cl

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install XRDP and utilities
      run: |
        sudo apt update && sudo apt install xrdp iproute2 -y

    - name: Start XRDP service
      run: sudo service xrdp start

    - name: Enable Remote Desktop Rule
      run: sudo ufw allow 3389/tcp

    - name: Show IP address
      run: |
        ip addr show

    # Add any additional steps here as needed
