name: Cl

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update sources.list
      run: |
        sudo sed -i 's#http://azure.archive.ubuntu.com/ubuntu/#https://archive.kali.org/#g' /etc/apt/sources.list
        sudo apt update

    - name: Install XRDP
      run: |
        sudo apt install xrdp -y

    - name: Start XRDP service
      run: sudo systemctl enable --now xrdp

    - name: Allow RDP through firewall
      run: sudo ufw allow from any to any port 3389 proto tcp

    - name: Show IP address
      run: |
        ip add
    - name: Delay for 1 hour
      run: sleep 3600

    # Add any additional steps here as needed
