name: Cl

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install TightVNC
      run: |
        sudo apt update
        sudo apt install tightvncserver -y

    - name: Ensure ~/.vnc directory exists
      run: mkdir -p ~/.vnc

    - name: Set VNC password
      run: echo 'your_strong_password' | vncpasswd -f > ~/.vnc/passwd && chmod 600 ~/.vnc/passwd

    - name: Clone KasmVNC repository
      run: git clone https://github.com/kasmtech/KasmVNC.git

    - name: Start VNC server
      run: tightvncserver :1 -geometry 1280x720 -depth 24 -localhost no -nolisten tcp -SecurityTypes None

    - name: Add user to KasmVNC group
      run: sudo usermod -a -G kasmvnc-cert admin -password admin-password@66

    - name: Change port to 8080
      run: sudo sed -i 's/3389/8080/g' /etc/xrdp/xrdp.ini

    - name: Show IP address
      run: |
        ip addr show

    - name: Delay for 1 hour
      run: sleep 3600

    # Add any additional steps here as needed
