name: Cl

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update sources.list
      run: |
        sudo sed -i 's#http://azure.archive.ubuntu.com/ubuntu/#https://archive.kali.org/#g' /etc/apt/sources.list
        sudo apt update

    - name: Install Ubuntu Desktop
      run: sudo apt install ubuntu-desktop -y

    - name: Install XRDP and utilities
      run: |
        sudo apt install xrdp iproute2 -y

    - name: Start XRDP service
      run: sudo service xrdp start

    - name: Enable Remote Desktop Rule
      run: sudo ufw allow 3389/tcp

    - name: Show IP address
      run: |
        ip addr show

    - name: Keep terminal session active for 1 hour
      run: sleep 3600

    # Add any additional steps here as needed
