name: Install KasmVNC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update sources.list
      run: |
        sudo sed -i 's#http://azure.archive.ubuntu.com/ubuntu/#https://archive.kali.org/#g' /etc/apt/sources.list
        sudo apt update

    - name: Download KasmVNC
      run: wget https://github.com/kasmtech/KasmVNC/releases/download/v1.3.0/kasmvncserver_jammy_1.3.0_amd64.deb

    - name: Install KasmVNC
      run: sudo apt-get install ./kasmvncserver_*.deb

    - name: Add user to ssl-cert group
      run: sudo addgroup $USER ssl-cert -user=admin -password=password@66

    - name: Start VNC server
      run: vncserver 

    - name: Tail VNC logs
      run: tail -f ~/.vnc/*.log

    - name: Start VNC server with Mate desktop
      run: vncserver -select-de mate -user=admin -password=password@66

    - name: Set VNC password
      run: vncpasswd -u my_username -w -r

    - name: List VNC servers
      run: vncserver -list -user=admin -password=password@66

    # Add any additional steps here as needed
