name: Kasm Install with Telebit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Install Telebit via curl command with email provided
    - name: Install Telebit
      run: curl https://get.telebit.io/ | bash -s -- peyisa6677@hisotyr.com

    # Change directory to /tmp
    - name: Change directory to /tmp
      run: cd /tmp

    # Download Kasm release archive
    - name: Download Kasm release archive
      run: |
        curl -O https://kasm-static-content.s3.amazonaws.com/kasm_release_1.15.0.06fdc8.tar.gz

    # Extract Kasm release archive
    - name: Extract Kasm release archive
      run: |
        tar -xf kasm_release_1.15.0.06fdc8.tar.gz

    # Run Kasm installation script with 'yes' response
    - name: Run Kasm installation script with 'yes' response
      run: |
        yes | sudo bash /tmp/kasm_release/install.sh

    # Provide Telebit details and start tunnel at port 443
    - name: Provide Telebit details and start tunnel at port 443
      run: |
        telebit http 443 &

    # Display IP address
    - name: Display IP address
      run: ip addr show

    # Delay for 1 hour
    - name: Delay for 1 hour
      run: sleep 3600
