name: VNC Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update package lists
      run: |
        sudo apt update

    - name: Install XFCE4 and TightVNCServer
      run: |
        sudo apt install xfce4 xfce4-goodies tightvncserver -y

    - name: Configure VNC Server
      run: |
        vncserver -geometry 1920x1080 -depth 24 -localhost :1
        echo "password" | vncpasswd -f > ~/.vnc/passwd
        vncserver -kill :1

    - name: Backup and Configure xstartup for XFCE4
      run: |
        mv ~/.vnc/xstartup ~/.vnc/xstartup.bak
        echo '#!/bin/bash' >> ~/.vnc/xstartup
        echo 'xrdb $HOME/.Xresources' >> ~/.vnc/xstartup
        echo 'startxfce4 &' >> ~/.vnc/xstartup
        chmod +x ~/.vnc/xstartup

    - name: Start VNC Server
      run: |
        vncserver -localhost

    - name: SSH Tunnel to VNC Server
      run: ssh -L 59000:localhost:5901 -C -N -l sammy your_server_ip
