name: Kasm Install

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Change directory to /tmp
      run: cd /tmp

    - name: Download Kasm release archive
      run: curl -O https://kasm-static-content.s3.amazonaws.com/kasm_release_1.15.0.06fdc8.tar.gz

    - name: Extract Kasm release archive
      run: tar -xf kasm_release_1.15.0.06fdc8.tar.gz

    - name: Run Kasm installation script with 'yes' response
      run: |
        yes | sudo bash kasm_release/install.sh

    - name: Manually edit xstartup
      run: |
        # Instructions to manually edit the xstartup file
        # You may need to open the file in a text editor and make the necessary changes

    - name: Troubleshoot select-de.sh
      run: |
        # Investigate why select-de.sh is failing to execute
        # Check for any errors in the script or missing dependencies

    - name: Display IP address
      run: ip addr show

    - name: Delay for 1 hour
      run: sleep 3600
