name: Kasm Install with Zrok

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Change directory to /tmp
    - name: Change directory to /tmp
      run: cd /tmp

    # Download Zrok release archive
    - name: Download Zrok release archive
      run: |
        curl -L -O https://github.com/openziti/zrok/releases/download/v0.4.26/zrok_0.4.26_linux_amd64.tar.gz

    # Extract Zrok release archive
    - name: Extract Zrok release archive
      run: |
        tar -xf zrok_0.4.26_linux_amd64.tar.gz

    # Run Zrok invite command
    - name: Run Zrok invite command
      run: |
        /tmp/zrok/zrok invite

    # Provide email input for Zrok invitation
    - name: Provide email input for Zrok invitation
      run: |
        echo "peyisa6677@hisotyr.com" | /tmp/zrok/zrok invite

    # Change directory to /tmp
    - name: Change directory to /tmp
      run: cd /tmp

    # Download Kasm release archive
    - name: Download Kasm release archive
      run: |
        curl -O https://kasm-static-content.s3.amazonaws.com/kasm_release_1.15.0.06fdc8.tar.gz

    # Extract Kasm release archive
    - name: Extract Kasm release archive
      run: |
        tar -xf kasm_release_1.15.0.06fdc8.tar.gz

    # Run Kasm installation script with 'yes' response
    - name: Run Kasm installation script with 'yes' response
      run: |
        yes | sudo bash /tmp/kasm_release/install.sh

    # Provide Zrok details and start tunnel at port 443
    - name: Provide Zrok details and start tunnel at port 443
      run: |
        /tmp/zrok/zrok connect http 443 &

    # Display IP address
    - name: Display IP address
      run: ip addr show

    # Delay for 1 hour
    - name: Delay for 1 hour
      run: sleep 3600
