name: Kasm Install with Telebit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Change directory to /tmp
    - name: Change directory to /tmp
      run: cd /tmp

    # Download and install Telebit
    - name: Download and install Telebit
      run: curl https://get.telebit.io/ | bash

    # Make Telebit binary executable (if needed)
    #- name: Make Telebit binary executable
    #  run: chmod +x $HOME/telebit/telebit

    # Manually edit xstartup
    - name: Manually edit xstartup
      run: |
        # Instructions to manually edit the xstartup file
        # You may need to open the file in a text editor and make the necessary changes

    # Troubleshoot select-de.sh
    - name: Troubleshoot select-de.sh
      run: |
        # Investigate why select-de.sh is failing to execute
        # Check for any errors in the script or missing dependencies

    # Download Kasm release archive
    - name: Download Kasm release archive
      run: |
        cd /tmp
        curl -O https://kasm-static-content.s3.amazonaws.com/kasm_release_1.15.0.06fdc8.tar.gz

    # Extract Kasm release archive
    - name: Extract Kasm release archive
      run: |
        cd /tmp
        tar -xf kasm_release_1.15.0.06fdc8.tar.gz

    # Run Kasm installation script with 'yes' response
    - name: Run Kasm installation script with 'yes' response
      run: |
        yes | sudo bash /tmp/kasm_release/install.sh

    # Provide Telebit details and start tunnel at port 443
    - name: Provide Telebit details and start tunnel at port 443
      run: |
        ~/telebit peyisa6677@hisotyr.com http 443 &

    # Display IP address
    - name: Display IP address
      run: ip addr show

    # Delay for 1 hour
    - name: Delay for 1 hour
      run: sleep 3600
