#!/bin/bash

# Install Kali Linux
# Assuming installation steps here

# Open terminal
gnome-terminal &

# Wait for terminal to open
sleep 5

# Run commands in terminal
gnome-terminal --tab -- bash -c '
echo "Running updates..."
sudo apt update && sudo apt upgrade -y;
echo "Installing XFCE desktop environment..."
sudo apt install kali-desktop-xfce -y;
echo "Installing XRDP..."
sudo apt install xrdp -y;
echo "Starting XRDP service..."
sudo service xrdp start;
echo "Displaying IP address...";
ip add | grep inet; # Show IP address
bash'

