name: CI

on: [push, workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update ngrok
      run: |
        sudo apt update
        sudo apt install ngrok-client
        ngrok update
    - name: Auth
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Create Tunnel
      run: ./ngrok tcp 3389
