name: Cl

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip -O ngrok.zip

    - name: Extract ngrok
      run: unzip ngrok.zip

    - name: Find ngrok binary
      run: |
        NGROK_BINARY=$(find . -name "ngrok" -type f)
        echo "Found ngrok binary at: $NGROK_BINARY"
        chmod +x $NGROK_BINARY

    - name: Auth
      run: $NGROK_BINARY authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS
      run: sudo sed -i 's/.*#Port 22/Port 22/' /etc/ssh/sshd_config && sudo service ssh restart

    - name: Enable Remote Desktop Rule
      run: sudo ufw allow 3389/tcp

    - name: Create Tunnel
      run: $NGROK_BINARY tcp 3389
