name: Kasm Install

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Change directory to /tmp
      run: cd /tmp

    - name: Download Kasm release archive
      run: curl -O https://kasm-static-content.s3.amazonaws.com/kasm_release_1.15.0.06fdc8.tar.gz

    - name: Extract Kasm release archive
      run: tar -xf kasm_release_1.15.0.06fdc8.tar.gz

    - name: Run Kasm installation script
      run: ls

    - name: Delay for 1 hour
      run: sleep 3600
