name: Kasm Install

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Change directory to /tmp
      run: cd /tmp

    - name: Download Kasm installation script
      run: curl -O https://kasm-static-content.s3.amazonaws.com/install.sh

    - name: Run Kasm installation script
      run: sudo bash install.sh

    - name: Delay for 1 hour
      run: sleep 3600
