name: CI

on: [push, workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download latest ngrok binary
      run: |
        curl -s https://ngrok.com/download | grep -o -m 1 'https://bin.equinox.io/.*/ngrok-stable-linux-amd64.zip' | wget -i - -O ngrok.zip
        unzip -o ngrok.zip
    - name: Move ngrok binary to /usr/local/bin
      run: |
        sudo mv ngrok /usr/local/bin/
        sudo chmod +x /usr/local/bin/ngrok
    - name: Verify ngrok version
      run: |
        ngrok version
    - name: Auth
      run: /usr/local/bin/ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Create Tunnel
      run: |
        /usr/local/bin/ngrok tcp 3389 &
        sleep 10
        curl -s http://localhost:4040/api/tunnels | jq '.tunnels[0].public_url'
